spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: fee8f1b7a5cf64c699d90a0599b4ee7d
            redirect-uri: http://175.45.195.13:3000/oauth2/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
